export const FAKE_DATA = {
  workouts: {
    names: ['push', 'pull', 'legs'],
  },
  exercises: {
    names: [
      'push-ups',
      'pull-ups',
      'sit-ups',
      'squats',
      'jumping jacks',
      'plank',
      'lunges',
      'burpees',
      'deadlifts',
      'bench press',
      'dumbbell rows',
      'shoulder press',
      'bicep curls',
      'tricep dips',
      'leg press',
      'calf raises',
      'mountain climbers',
      'russian twists',
      'kettlebell swings',
      'box jumps',
      'battle ropes',
      'wall sits',
      'barbell hip thrusts',
      'flutter kicks',
      'hanging leg raises',
      'farmers walk',
      'medicine ball slams',
      'resistance band exercises',
      'rowing machine',
      'elliptical workout',
      'cycling',
      'swimming laps',
      'yoga session',
      'pilates class',
      'hiit workout',
      'crossfit wod',
      'zumba dance fitness',
      'kickboxing',
      'muay thai training',
      'martial arts drills',
      'bodyweight circuit',
      'trx suspension training',
      'powerlifting session',
      'functional training',
      'core strengthening routine',
      // Additional weightlifting exercises
      'romanian deadlifts',
      'clean and jerk',
      'snatch',
      'front squats',
      'overhead squats',
      'sumo deadlifts',
      'incline bench press',
      'cable rows',
      'hammer curls',
      'skull crushers',
      'leg extensions',
      'leg curls',
      'seated shoulder press',
      'pull-downs',
      'barbell shrugs',
      'reverse flyes',
      'lateral raises',
      'preacher curls',
      'decline bench press',
      'hack squats',
      'pullovers',
      'close-grip bench press',
      'standing calf raises',
      'trap bar deadlifts',
      'arnold press',
      'wrist curls',
      'cable crunches',
      'glute bridges',
    ],
  },
}
